<?php
/**
* Anthrocon dealers module.
*
* This module holds dealer and Dealer Room staff-specific functionality.
*/



/**
* Return an array of permissions for this module.
*/
function anthrocon_dealers_perm() {
	$retval = array("view dealer table sales");
	return($retval);
}


/**
* Return an array of menu options.
*/
function anthrocon_dealers_menu() {

	$retval = array();

	$retval["admin/dealer"] = array(
		"title" => "View Dealer Tables",
		"page callback" => "anthrocon_dealers_main",
		"access arguments" => array("view dealer table sales"),
		);

	return($retval);

} // End of anthrocon_dealers_menu()


/**
* Our main page.
*/
function anthrocon_dealers_main() {

	$retval = "";

	$retval = drupal_get_form("anthrocon_dealers_form");

	return($retval);

} // End of anthrocon_dealers_main()


function anthrocon_dealers_form() {

	$retval = array();

	$retval["tables"] = array(
		"#type" => "fieldset",
		"#title" => t("Dealer Tables"),
		);

	$retval["tables"]["view"] = array(
		"#type" => "submit",
		"#value" => t("View"),
		);

	$retval["tables"]["download"] = array(
		"#type" => "submit",
		"#value" => t("Download"),
		);

	return($retval);

} // End of anthrocon_dealers_form()


function anthrocon_dealers_form_submit($form, $form_state) {
//print_r($form);
//print_r($form_state);

} // End of anthrocon_dealers_submit()


